### ISSUE TITLE
module 'cv2' has no attribute 'cuda_SparsePyrLKOpticalFlow'

### ISSUE THREAD

**Issue by MrL-CV** [jiy173/selfievideostabilization#2]
Should I re-compile a new version of OpenCV-python with CUDA?

**Comment by asd18214** [comment]
> Should I re-compile a new version of OpenCV-python with CUDA?

Yes, you have to do this. Then you have to use CMAKE to compile opencv-python and opencv-contrib-python with CUDA.

**Comment by asd18214** [comment]
> Should I re-compile a new version of OpenCV-python with CUDA?

Yes, you have to do this. Then you need to use CMAKE to compile opencv-python and opencv-contrib-python with CUDA.

**Comment by MrL-CV** [comment]
Excuse me, Could you tell me the appropriate version of the CUDA as well as the version of OpenCV and python? Thanks

**Comment by Embarrassing1** [comment]
Excuse me, I recently had the same problem, have you solved it?

**Comment by mhmtsarigul** [comment]
Still same problem. anyone knowing the solution?
